apiVersion: apps/v1
kind: Deployment
metadata:
  name: simgerchev-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simgerchev-website
  template:
    metadata:
      labels:
        app: simgerchev-website
    spec:
      containers:
        - name: simgerchev-website
          image: simgerchev-website
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: simgerchev-website
spec:
  selector:
    app: simgerchev-website
  ports:
    - name: http
      port: 80
      targetPort: 5173
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simgerchev-website
spec:
  ingressClassName: traefik
  rules:
    - host: simgerchev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simgerchev-website
                port:
                  number: 80
