version: "3.8"
services:
  react-app:
    build: ../app/simgerchev-website
    ports:
      - "5173:5173"
    volumes:
      - ../app/simgerchev-website:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
